{
 "title": "Student App Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "HPA Replicas Status",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{namespace=\"student-app\"}",
     "legendFormat": "HPA Current replicas"
    },
    {
     "expr": "kube_horizontalpodautoscaler_status_desired_replicas{namespace=\"student-app\"}",
     "legendFormat": "HPA Desired replicas"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_max_replicas{namespace=\"student-app\"}",
     "legendFormat": "HPA Max Replicas"
    }
   ]
  },
  {
   "title": "CPU Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"student-app\",container=\"student-app\"}[5m])) * 100",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"student-app\",container=\"student-app\"}) / 1024 / 1024",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Application Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{namespace=\"student-app\", container=\"student-app\"}"
    }
   ]
  },
  {
   "title": "Log Count by Level (stdout)",
   "type": "timeseries",
   "description": "Standard output in every 5 minutes",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(count_over_time(({namespace=\"student-app\",container=\"student-app\"})[$__auto])) by (stream)",
     "legendFormat": "{{label}}"
    }
   ]
  }
 ]
}