apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: student-app
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/student
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: postgres
